# Generated by Django 3.0.6 on 2020-05-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('store_date_type', models.IntegerField(choices=[(1, '元旦'), (2, '春节'), (3, '清明节'), (4, '劳动节'), (5, '端午节'), (6, '中秋节'), (7, '国庆节'), (8, '调休')])),
                ('date_code', models.IntegerField(default=2)),
            ],
        ),
    ]
